package com.javarush.task.task35.task3513;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
import java.awt.event.*;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
public class Controller extends KeyAdapter {                                                                                                                                                                                                                                                                                                            
    private Model model;                                                                                                                                                                                                                                                                                                            
    private View view;                                                                                                                                                                                                                                                                                                            
    private static int WINNING_TILE = 2048;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                
    public Controller(Model model){                                                                                                                                                                                                                                                                                                            
        this.model = model;                                                                                                                                                                                                                                                                                                            
        view = new View(this);                                                                                                                                                                                                                                                                                                            
    }   
    public View getView(){
    return view;
}                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                
    @Override                                                                                                                                                                                                                                                                                                            
    public void	 keyPressed(KeyEvent e){                                                                                                                                                                                                                                                                                                            
        	int o = e.getKeyCode();                                                                                                                                                         
         if(o == KeyEvent.VK_ESCAPE)                                                                                                                                                       
               this.resetGame();                                                                                                                                                        
          if(!model.canMove() ){                                                                                                                                                      
             view.isGameLost = true;                                                                                                                                                      
          }                                                                                                                                                        
          if(!(view.isGameLost &&   view.isGameWon)){                                                                                                                                                      
              if(o ==  KeyEvent.VK_LEFT){                                                                                                                                                      
                  model.left();                                                                                                                                                      
              }                                                                                                                                                      
              if(o ==  KeyEvent.VK_RIGHT){                                                                                                                                                      
                  model.right();                                                                                                                                                      
              }                                                                                                                                                      
              if(o ==  KeyEvent.VK_UP){                                                                                                                                                      
                  model.up();                                                                                                                                                      
              }                                                                                                                                                      
              if(o ==  KeyEvent.VK_DOWN){                                                                                                                                                      
                  model.down();                                                                                                                                                      
              }                                                                                                                                                      
              if(o == KeyEvent.VK_Z){
                    model.rollback();
              }
              if(o == KeyEvent.VK_R){
                  model.randomMove();
              }
              if(o == KeyEvent.VK_A){
                  model.autoMove();
              }
          }                                                                                                                                                        
           if(model.maxTile == WINNING_TILE)                                                                                                                                                      
             view.isGameWon = true;

        if(o == KeyEvent.VK_LEFT || o == KeyEvent.VK_RIGHT || o == KeyEvent.VK_UP || o == KeyEvent.VK_DOWN
        || o == KeyEvent.VK_R || o == KeyEvent.VK_A)  model.addTile();
          view.repaint();

                                                                                                                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                
    public Tile[][] getGameTiles(){                                                                                                                                                                                                                                                                                                            
        return model.getGameTiles();                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                
    public int getScore(){                                                                                                                                                                                                                                                                                                            
        return model.score;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                
    public void resetGame(){                                                                                                                                                         
        model.resetGameTiles();                                                                                                                                                                                                                                                                                           
        view.isGameWon = false;                                                                                                                                                                                                                                                                                                            
        view.isGameLost = false;                                                                                                                                                                                                                                                                                                            
        model.score = 0;                                                                                                                                                        
        //model.maxTile = 0;                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                   
    }                                                                                                                                                                                                                                                                                                            
}