package com.javarush.task.task35.task3513;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
import java.util.*;

public class Model { // Он будет ответственен за все манипуляции производимые с игровым полем.                                                                                                                                                                                                                                                                                                            
    private static final int FIELD_WIDTH = 4;                                                                                                                                                                                                                                                                                                            
    private Tile[][] gameTiles;
    int score = 0; // текущий счет                                                                                                                                                                                                                                                                                                            
    int maxTile = 0; // максимальный вес плитки
    private Stack<Tile[][]> previousStates = new Stack<>(); // для отмены действия храним состояние поля
    private Stack<Integer> previousScores = new Stack<>();// для отмены действия храним состояние счета
    private boolean isSaveNeeded = true;



    public Model() {                                                                                                                                                                                                                                                                                                            
        resetGameTiles();
    }

    public void autoMove(){
        PriorityQueue<MoveEfficiency> priorityQueue = new PriorityQueue(4, Collections.reverseOrder());
        priorityQueue.add( getMoveEfficiency(()-> left()) );
        priorityQueue.add( getMoveEfficiency(()-> right()) );
        priorityQueue.add( getMoveEfficiency(()-> up()) );
        priorityQueue.add( getMoveEfficiency(()-> down()) );
        MoveEfficiency moveEFF = priorityQueue.peek();
        Move move = moveEFF.getMove();
        move.move();

    }

    MoveEfficiency getMoveEfficiency(Move move){
        //принимает один параметр типа move, и возвращает объект типа MoveEfficiency
        // описывающий эффективность переданного хода. Несколько советов:
        //а) не забудь вызывать метод rollback, чтобы восстановить корректное игровое состояние;
        //б) в случае, если ход не меняет состояние игрового поля, количество пустых плиток и
        // счет у объекта MoveEfficiency сделай равными -1 и 0 соответственно;
        //в) выполнить ход можно вызвав метод move на объекте полученном в качестве параметра.
        move.move();
        if (hasBoardChanged()){
            rollback();
            return new MoveEfficiency(getEmptyTiles().size(), score, move );
        }

        rollback();

        return new MoveEfficiency(-1, 0, move);
    }

    boolean hasBoardChanged(){ //если вес плиток в массиве gameTiles отличается от
                               // веса плиток в верхнем массиве стека previousStates
        Tile[][] tilesInStack = previousStates.peek();
        int weightTilesInStack = 0;

        for (int y = 0; y < FIELD_WIDTH; y++) { // высота
            for (int x = 0; x < FIELD_WIDTH; x++) { // ширина
                Tile tile = tilesInStack[y][x];
                weightTilesInStack+= tile.value;
            }
        }

        int weightGameTiles = 0;

        for (int y = 0; y < FIELD_WIDTH; y++) { // высота
            for (int x = 0; x < FIELD_WIDTH; x++) { // ширина
                Tile tile = gameTiles[y][x];
                weightGameTiles += tile.value;
            }
        }

        return (weightTilesInStack != weightGameTiles);
    }

    public void randomMove(){
        int n = ((int) (Math.random() * 100)) % 4;
        if (n == 0) left();
        if (n == 1) right();
        if (n == 2) up();
        if (n == 3) down();
    }

    private void saveState(Tile[][] tiles){
        Tile[][] newTiles = createCloneTiles(tiles);
        previousStates.push(newTiles);
        previousScores.push(score);
        isSaveNeeded = false;
    }

    private Tile[][] createCloneTiles(Tile[][] tiles){
        Tile[][] emptyTiles = new Tile[FIELD_WIDTH][FIELD_WIDTH];
        for (int y = 0; y < FIELD_WIDTH; y++) { // высота
            for (int x = 0; x < FIELD_WIDTH; x++) { // ширина
                Tile newTile = new Tile();
                Tile tile = tiles[y][x];
                newTile.value = tile.value;
                emptyTiles[y][x] = newTile;
            }
        }
        return emptyTiles;
    }

    void rollback(){
        if (!previousStates.isEmpty())
        gameTiles = previousStates.pop();
        if (!previousScores.isEmpty())
        score = previousScores.pop();

    }
                                                                                                                                                                                                                                                                                                                
    public Tile[][] getGameTiles(){                                                                                                                                                                                                                                                                                                            
        return gameTiles;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                
    public boolean canMove(){
                                                                                                                                                                                                                                                                                                                    
        if(!getEmptyTiles().isEmpty()) return true;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    
        for(int i=0; i < gameTiles.length-1; i++){                                                                                                                                                                                                                                                                                                            
            for(int j=0; j < gameTiles.length; j++){                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                            
                if(gameTiles[i][j].value == gameTiles[i + 1][j].value){ // по вертикали                                                                                                                                                                                                                                                                                                            
                   return true;                                                                                                                                                                                                                                                                                                            
                }                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    
        for(int i=0; i < gameTiles.length; i++){                                                                                                                                                                                                                                                                                                            
            for(int j=0; j < gameTiles.length-1; j++){                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                            
                if(gameTiles[i][j].value == gameTiles[i][j + 1].value){ // по горизонтали                                                                                                                                                                                                                                                                                                            
                   return true;                                                                                                                                                                                                                                                                                                            
                }                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            

        return false;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                
    public int getScore(){                                                                                                                                                                                                                                                                                                            
        return score;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    void addTile() {
        List<Tile> emptyTiles = getEmptyTiles();                                                                                                                                                                                                                                                                                                            
        if (emptyTiles.size() > 0)                                                                                                                                                                                                                                                                                                            
            emptyTiles.get((int) (emptyTiles.size() * Math.random())).value = (Math.random() < 0.9 ? 2 : 4);                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    //который будет смотреть какие плитки пустуют и, если такие имеются,                                                                                                                                                                                                                                                                                                            
    //менять вес одной из них, выбранной случайным образом, на 2 или 4 (на 9 двоек должна приходиться 1 четверка).                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    private List<Tile> getEmptyTiles() {  // возвращающий список свободных плиток в массиве gameTiles.                                                                                                                                                                                                                                                                                                            
        List<Tile> tileList = new ArrayList<>();                                                                                                                                                                                                                                                                                                            
        for (int y = 0; y < FIELD_WIDTH; y++) { // высота                                                                                                                                                                                                                                                                                                            
            for (int x = 0; x < FIELD_WIDTH; x++) { // ширина                                                                                                                                                                                                                                                                                                            
                Tile tile = gameTiles[y][x];                                                                                                                                                                                                                                                                                                            
                if (tile.value == 0) tileList.add(tile);                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
        return tileList;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    void resetGameTiles() {                                                                                                                                                                                                                                                                                                            
        this.gameTiles = new Tile[FIELD_WIDTH][FIELD_WIDTH];                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        for (int y = 0; y < FIELD_WIDTH; y++) { // высота                                                                                                                                                                                                                                                                                                            
            for (int x = 0; x < FIELD_WIDTH; x++) { // ширина                                                                                                                                                                                                                                                                                                            
                gameTiles[y][x] = new Tile();                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
        addTile();                                                                                                                                                                                                                                                                                                            
        addTile();                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
    // при необходимости начать новую игру,                                                                                                                                                                                                                                                                                                            
    // не приходилось создавать новую модель, а можно было бы просто вернуться в начальное состояние                                                                                                                                                                                                                                                                                                            
    //вызвав его. Уровень доступа должен быть шире приватного.                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    private boolean compressTiles(Tile[] tiles) { // Сжатие плиток все пустые на пример справа 4 2 0 2                                                                                                                                                                                                                                                                                                            
        boolean isModify = false;                                                                                                                                                                                                                                                                                                            
        for (int z = 0; z < tiles.length; z++) {                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
            for (int i = 0; i < tiles.length; i++) {                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                if ((i + 1) == tiles.length) break;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                Tile current = tiles[i];                                                                                                                                                                                                                                                                                                            
                Tile next = tiles[i + 1];                                                                                                                                                                                                                                                                                                            
                if ((current.value == next.value) && (current.value == 0)) continue;                                                                                                                                                                                                                                                                                                            
                Tile buffer = null;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                if (tiles[i].value == 0) {                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                    buffer = tiles[i];                                                                                                                                                                                                                                                                                                            
                    tiles[i] = next;                                                                                                                                                                                                                                                                                                            
                    tiles[i + 1] = buffer;                                                                                                                                                                                                                                                                                                            
                    isModify = true;                                                                                                                                                                                                                                                                                                            
                }                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        return isModify;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    private boolean mergeTiles(Tile[] tiles) { // Слияние плиток                                                                                                                                                                                                                                                                                                            
        boolean isModify = false;                                                                                                                                                                                                                                                                                                            
        compressTiles(tiles);                                                                                                                                                                                                                                                                                                            
        for (int i = 0; i < tiles.length; i++) {                                                                                                                                                                                                                                                                                                            
            if ((i + 1) == tiles.length) break;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
            Tile current = tiles[i];                                                                                                                                                                                                                                                                                                            
            Tile next = tiles[i + 1];                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
            if ((current.value == next.value) && (current.value != 0)) {                                                                                                                                                                                                                                                                                                            
                current.value = current.value + next.value;                                                                                                                                                                                                                                                                                                            
                score = score + current.value;                                                                                                                                                                                                                                                                                                            
                next.value = 0;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                maxTile = Math.max(current.value, maxTile);                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                compressTiles(tiles);                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                isModify = true;                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }


        return isModify;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
    //1. Если выполняется условие слияния плиток, проверяем является ли новое значения больше максимального и при                                                                                                                                                                                                                                                                                                            
    // необходимости меняем значение поля maxTile.                                                                                                                                                                                                                                                                                                            
    //2. Увеличиваем значение поля score на величину веса плитки образовавшейся в результате слияния.                                                                                                                                                                                                                                                                                                            
    //                                                                                                                                                                                                                                                                                                            
    //P.S. Когда мы будем реализовывать методы движения, сжатие будет всегда выполнено перед слиянием,                                                                                                                                                                                                                                                                                                            
    // таким образом можешь считать, что в метод mergeTiles всегда передается массив плиток без пустых в середине.                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    public void left() {
        if (isSaveNeeded){
            saveState(gameTiles);
        }

        boolean isCompress = false;                                                                                                                                                                                                                                                                                                            
        boolean isMerge = false;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        for (Tile[] tiles : gameTiles) {                                                                                                                                                                                                                                                                                                            
            isCompress = compressTiles(tiles);                                                                                                                                                                                                                                                                                                            
            isMerge = mergeTiles(tiles);                                                                                                                                                                                                                                                                                                            
            if (isMerge && isCompress) {                                                                                                                                                                                                                                                                                                            
                addTile();                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
            isCompress = false;                                                                                                                                                                                                                                                                                                            
            isMerge = false;                                                                                                                                                                                                                                                                                                            
        }
        isSaveNeeded = true;
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    public void right() {
        saveState(gameTiles);
                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        left();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    public void up() {
        saveState(gameTiles);

        rotateClockwise();                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        left();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    public void down() {
        saveState(gameTiles);

        rotateClockwise();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        left();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
        rotateClockwise();                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
    public void rotateClockwise() {                                                                                                                                                                                                                                                                                                            
        Tile[][] resultArray = new Tile[gameTiles[0].length][gameTiles.length];                                                                                                                                                                                                                                                                                                            
        for (int i = 0; i < gameTiles.length; i++) {                                                                                                                                                                                                                                                                                                            
            for (int j = 0; j < gameTiles[i].length; j++) {                                                                                                                                                                                                                                                                                                            
                resultArray[j][gameTiles.length - i - 1] = gameTiles[i][j];                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                            
        gameTiles = resultArray;                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
}