package com.javarush.task.task18.task1828;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
/*                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
Прайсы 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
*/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
import java.io.*;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
import java.util.*;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
public class Solution {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    public static void main(String[] args) throws Exception {
        for (String f:args) System.out.println(f);
        BufferedReader readerSystem = new BufferedReader(new InputStreamReader(System.in));    // Создаем поток для чтения имени файла                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        String fileName = readerSystem.readLine();                                             // Читаем имя файла для CrUD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        readerSystem.close();                                                                   // Закрываем поток для чтения                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        List<String> map = new ArrayList<>();                                                   // Создаем список для хранения строк файла                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        if(args.length > 0){                   // Если есть аргументы
            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream (fileName))); //  Открываем поток для  чтения из файла      
            while(reader.ready()){                                                                             // Пока есть строки                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                String line = reader.readLine();
                System.out.println("прочитана строка " + line);// Читаем строку
                String idthis = line.substring(0,8).replaceAll(" ", "");          // Получаем первые 8 символов id отбрасываем пробелы
                if(idthis.equals(args[1])){                                       // Если полученный id соответствует id из параметров
                    if(args[0].equals("-u")){                                                  // Если полученный параметр соответствует -u
                        String mapId = String.format("%-8s", args[1]);   // Форматируем для записи в строку  id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        String productName = String.format("%-30.30s",args[2]);             // Форматируем для записи в строку productName                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        String price = String.format(Locale.ROOT, "%-8s", args[3]); // Форматируем для записи в строку price                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                        String quantity = String.format("%-4s", args[4]);   // Форматируем для записи в строку quantity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        String forFile = (mapId + productName + price + quantity);          // Собираем строку для записи
                        map.add(forFile); // добавляем обновленную строку
                        continue; // переходим к чтению следующей строки
                    } else if(args[0].equals("-d")){
                        continue; // Не добавляем данную строку и переходим к чтению следующей строки
                    }
                }
                map.add(line);      // добавляем неизмененную строку                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            }
            reader.close();  // закрываем поток для чтения
            BufferedWriter writer = new BufferedWriter(new FileWriter(fileName)); // Открываем поток для записи
            int size = 0; // подсчет строк
            for(String line:map) {  
              if(size!=0){writer.newLine();} // Если первая строка переход на следую строку не добавляем
              writer.write(line);
              size++;
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
            writer.close();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        }
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
}